# Generated by Django 6.0 on 2025-12-24 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('Calculus I', 'Calculus I'), ('Calculus II', 'Calculus II'), ('Calculus III', 'Calculus III')], max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('quiz_type', models.CharField(choices=[('Practical', 'Practical'), ('Theoretical', 'Theoretical')], max_length=50)),
                ('evaluation_method', models.CharField(choices=[('Self-Eval', 'Self-Eval'), ('Automated', 'Automated')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('model_answer', models.TextField()),
                ('question_order', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
