# Generated by Django 6.0 on 2025-12-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='accepted_answers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
