# Generated by Django 6.0 on 2026-01-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_topicstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='domain',
            field=models.CharField(choices=[('Calculus', 'Calculus'), ('Linear Algebra', 'Linear Algebra')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('Practical', 'Practical'), ('Theoretical', 'Theoretical'), ('Revision', 'Revision')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.CharField(choices=[('Calculus I', 'Calculus I'), ('Calculus II', 'Calculus II'), ('Calculus III', 'Calculus III'), ('Mechanics', 'Mechanics')], max_length=100),
        ),
    ]
