# Generated by Django 6.0 on 2026-01-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quiz_domain_alter_quiz_quiz_type_alter_quiz_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='domain',
            field=models.CharField(choices=[('Calculus', 'Calculus'), ('Linear Algebra', 'Linear Algebra')], max_length=100),
        ),
    ]
