# Generated by Django 6.0 on 2026-01-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_alter_quiz_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='domain',
            field=models.CharField(choices=[('Calculus', 'Calculus'), ('Linear Algebra', 'Linear Algebra'), ('Statistics', 'Statistics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.CharField(choices=[('Calculus I', 'Calculus I'), ('Calculus II', 'Calculus II'), ('Calculus III', 'Calculus III'), ('Probability', 'Probability'), ('Mechanics', 'Mechanics')], max_length=100),
        ),
    ]
